### ISSUE TITLE
Hugo Theme

### ISSUE THREAD

**Issue by BrandonRomano** [mcastilho/mcastilho.github.io#2]
Hey @mcastilho.

Seen your blog posts come up a few times in /r/golang -- was curious about your them you use for the layout.

I've seen it before (http://npf.io/) and was curious where this theme originally comes from?  Is this a theme straight from the Hugo site?

Simply curious, as I am a big fan of it (and may want to use it myself)
- Brandon

**Comment by mcastilho** [comment]
This theme is a slight customized version of the Hyde theme from Hugo author - https://github.com/spf13/hyde
